#!/bin/sh
echo "🚀 Running tests before push..."

if [ -f ".venv/bin/activate" ]; then
    . .venv/bin/activate
fi

pytest
STATUS=$?

if [ $STATUS -ne 0 ]; then
    echo "❌ Tests failed. Push aborted."
    exit 1
fi

echo "✔️ Tests passed. Proceeding with push."
exit 0