"""
Regression tests for ComaPy against Java COMA golden files.

Golden files were generated by running the Java COMA implementation on the
authors1/authors2 test data. These tests ensure ComaPy produces equivalent
results in terms of matched column pairs and similarity scores.
"""

import json
import time
from pathlib import Path

import pytest

from tests import df1, df2
from valentine.algorithms import ComaPy
from valentine.data_sources import DataframeTable

d1 = DataframeTable(df1, name="authors1")
d2 = DataframeTable(df2, name="authors2")

DATA_DIR = Path(__file__).parent / "data"


def _load_golden(filename: str) -> dict[tuple, float]:
    """Load golden file and convert keys back to match tuple format."""
    raw = json.loads((DATA_DIR / filename).read_text())
    result = {}
    for key_str, score in raw.items():
        parts = key_str.split("||")
        src_table, src_col = parts[0].split("|")
        tgt_table, tgt_col = parts[1].split("|")
        result[((src_table, src_col), (tgt_table, tgt_col))] = score
    return result


@pytest.fixture(scope="module")
def golden_schema_only():
    return _load_golden("coma_golden_schema_only.json")


@pytest.fixture(scope="module")
def golden_schema_instance():
    return _load_golden("coma_golden_schema_instance.json")


def test_coma_py_schema_only_same_pairs(golden_schema_only):
    """ComaPy must find the same column pairs as Java COMA (schema-only)."""
    matcher = ComaPy(use_instances=False)
    py_results = matcher.get_matches(d1, d2)

    golden_keys = set(golden_schema_only.keys())
    py_keys = set(py_results.keys())

    assert golden_keys.issubset(py_keys), f"Missing pairs from golden: {golden_keys - py_keys}"


def test_coma_py_schema_only_scores(golden_schema_only):
    """ComaPy scores must be within tolerance of Java COMA (schema-only)."""
    matcher = ComaPy(use_instances=False)
    py_results = matcher.get_matches(d1, d2)

    for key, golden_score in golden_schema_only.items():
        assert key in py_results, f"Missing match: {key}"
        assert py_results[key] == pytest.approx(golden_score, abs=0.05), (
            f"Score mismatch for {key}: Python={py_results[key]:.4f}, Java={golden_score:.4f}"
        )


def test_coma_py_schema_instance_same_pairs(golden_schema_instance):
    """ComaPy must find the same column pairs as Java COMA (schema+instance)."""
    matcher = ComaPy(use_instances=True)
    py_results = matcher.get_matches(d1, d2)

    golden_keys = set(golden_schema_instance.keys())
    py_keys = set(py_results.keys())

    assert golden_keys.issubset(py_keys), f"Missing pairs from golden: {golden_keys - py_keys}"


def test_coma_py_schema_instance_scores(golden_schema_instance):
    """ComaPy scores must be within tolerance of Java COMA (schema+instance)."""
    matcher = ComaPy(use_instances=True)
    py_results = matcher.get_matches(d1, d2)

    for key, golden_score in golden_schema_instance.items():
        assert key in py_results, f"Missing match: {key}"
        # Instance matching has larger score divergence due to TF-IDF differences
        assert py_results[key] == pytest.approx(golden_score, abs=0.25), (
            f"Score mismatch for {key}: Python={py_results[key]:.4f}, Java={golden_score:.4f}"
        )


def test_coma_py_performance():
    """ComaPy must complete matching within reasonable time."""
    matcher = ComaPy(use_instances=True)
    start = time.perf_counter()
    for _ in range(10):
        matcher.get_matches(d1, d2)
    elapsed = time.perf_counter() - start
    avg_ms = (elapsed / 10) * 1000
    # Must complete in under 5 seconds per match
    assert avg_ms < 5000, f"ComaPy too slow: {avg_ms:.0f}ms per match"
